### ISSUE TITLE
Week 2 Lecture Notes

### ISSUE THREAD

**Issue by ashleywilk** [Watts-College/paf-516-template#21]
Hello, 
The link for week 2 lecture notes takes me to lab 1 instructions. Is there anyway we can have the access to lecture notes? 

Thank you

**Comment by ykimasu** [comment]
Hi Ashleywilk, 

I got the same comment from another student, but wasn't able to identify the instruction you refer to. Can you locate the instruction link so that I can examine it?

Yushim

**Comment by ykimasu** [comment]
I was informed that the link is corrected. You should be able to see the note. If not, please let me know. 

https://watts-college.github.io/paf-516-template/lectures/MappingIntro.html#/intro-to-census-data
