### ISSUE TITLE
Final Dashboard Not Rendering

### ISSUE THREAD

**Issue by amourning1** [Watts-College/paf-516-template#23]
Hello,
I'm trying to render the dashboard for the final project, but the rendering process gets stuck partway through and will not produce the dashboard.  I’ve been customizing the dashboard template for Albuquerque, data, and the code appears to be complete. However, I can’t produce the dashboard to confirm its functionality.

Any advice would be greatly appreciated.

[Final Project - A. Mourningv.1.txt](https://github.com/user-attachments/files/17942545/Final.Project.-.A.Mourningv.1.txt)

**Comment by amourning1** [comment]
Update:  I have tried to split up the data steps into a separate file and store on a GitHub repository, but I still cant render my dashboard. Not sure if I am even on the right path, but would appreciate any advice. 

Dashboard Rmd: [Final Project - A. Mourningv.1.txt](https://github.com/user-attachments/files/17952340/Final.Project.-.A.Mourningv.1.txt)

Data preparation file: https://raw.githubusercontent.com/amourning1/Final-Dashboard-2024/refs/heads/main/data_preperation.%20new.R

GeoJason file: [processed_abq_mhv_change-geojason.txt](https://github.com/user-attachments/files/17952349/processed_abq_mhv_change-geojason.txt)

**Comment by ykimasu** [comment]
Annamia,
Thank you for the update. I am moving into the final project and let me see
what I can find about the issue.
Yushim

**Comment by amourning1** [comment]
Thank you for your helpful video! I was able to render my dashboard!

**Comment by ykimasu** [comment]
Great to hear that!
